[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn run:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[environments]
FLASK_APP = "app"
FLASK_ENV = "production"