"""Migración inicial completa

Revision ID: 77559306c971
Revises: 
Create Date: 2025-04-07 18:46:00.764045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77559306c971'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_pk')
    )
    # ### end Alembic commands ###
